version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  django:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
